# Etapa 1: Build (opcional si quieres compilar dentro del contenedor)
# FROM maven:3.9.6-eclipse-temurin-21 AS builder
# WORKDIR /app
# COPY . .
# RUN mvn clean package -DskipTests

# Etapa 2: Runtime
# FROM eclipse-temurin:21-jdk
# WORKDIR /app

# # Copiar el JAR (ajusta el nombre según el tuyo)
# COPY target/miapp.jar app.jar

# # Exponer el puerto del Spring Boot
# EXPOSE 8081

# # Ejecutar la app
# ENTRYPOINT ["java","-jar","app.jar"]
